Fix future attached to different loop error
The tests.integration.endpoints_test were failing on Python 3.8 and 3.9
because the endpoint fixture timed out waiting for the endpoint
processes to start up. It turns out that the endpoints were crashing,
but the error was being supressed by the serve_endpoint_silent
function. After disabling the output supression, the endpoints were
raising the following error:

RuntimeError: Task <Task pending name='endpoint-9d5067bf-bf7a-493b-a377-01c5fcd66802-handle-peer-requests' coro=<_execute_and_log_traceback() running at /home/jgpaul/workspace/proxystore/proxystore/p2p/task.py:31> cb=[exit_on_error() at /home/jgpaul/workspace/proxystore/proxystore/p2p/task.py:37]> got Future <Future pending> attached to a different loop

What was happening is that the PeerManager initialized in
proxystore.endpoint.serve.serve() was creating an asyncio.Lock
containing a future from an event loop creating in
serve_endpoint_silent. But the Quart server was being run in a new
event loop created at the end of serve(). To fix this, I created
a coroutine helper function for serve() so all of the initialization
can be done within the event loop created by the asyncio.run() call
in serve(). There were a couple testing bits of code which erroneously
created their own event loops because of this issue that I was able to
remove.